FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y install cron
RUN apt-get -y install rsync

WORKDIR /app
ADD crontab .
ADD backup.sh .
RUN chmod 0644 ./crontab
RUN chmod +x ./backup.sh
RUN touch /var/log/cron.log

# Create the user to run the command inside the crontab
RUN useradd -m -u 1000 -s /bin/bash ubuntu

# This "installs" the crontab file, to be ran by the created user
RUN crontab -u ubuntu crontab

CMD cron && tail -f /var/log/cron.log